name: Run Git pull on the dzine server

on:
  push:
    branches: [ "sample" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dzinehub

    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v0.1.7
      env:
        DEPLOYMENT_LOCATION: ${{ secrets.DEPLOYMENT_LOCATION }}

      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
       # key: ${{ secrets.SSH_KEY }}
        port: 22
        envs: DEPLOYMENT_LOCATION
        script: |
          cd $DEPLOYMENT_LOCATION
          git pull
